#!/usr/bin/env bash
# Copyright (c) Andrei Jiroh Halili
# SPDX-License-Identifier: MPL-2.0
set -e

if [[ $DEBUG != "" ]]; then
  set -x
fi

ROOT="$( cd -- "$(dirname "$0/")/../.." >/dev/null 2>&1 ; pwd -P )"
USERNAME=${USERNAME:-"ajhalili2006"}

ansible-playbook "$ROOT/ansible/arch/setup.yml" --extra-vars "username=$USERNAME" -vvvv
